

Global:
  infer_imgs: d:/data_class_img/test_out/bicycles-0a95600d-c3a5-447b-b4c9-9b3c503ddd08_0_2.jpg
  inference_model_dir: D:/Capcha/PaddleClas/output2/inference_model
  batch_size: 1
  use_gpu: True
  enable_mkldnn: True
  cpu_num_threads: 10
  enable_benchmark: True
  use_fp16: False
  ir_optim: True
  use_tensorrt: False
  gpu_mem: 8000
  enable_profile: False

PreProcess:
  transform_ops:
    - ResizeImage:
        resize_short: 256
    - CropImage:
        size: 224
    - NormalizeImage:
        scale: 0.00392157
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ""
        channel_num: 3
    - ToCHWImage:

PostProcess:
  main_indicator: Topk
  Topk:
    topk: 5
    class_id_map_file: D:/Capcha/PaddleClas/deploy/configs/labels.txt
  SavePreLabel:
    save_dir: D:/Capcha/PaddleClas/output2/inference_lable
