Global:
  infer_imgs: d:/data_class_img/test
  batch_size: 1
  use_gpu: True
  gpu_mem: 1000
  save_log_path: ./log
  inference_model_dir: d:/Capcha/PaddleClas/output2/inference_model
  use_tensorrt: False
  ir_optim: True
  use_fp16: False 
  enable_mkldnn: False
  cpu_threads: 10
  cpu_num_threads: 10
  benchmark: False
  use_onnx: False
  enable_profile: False

PostProcess:
  Topk:
    topk: 5
    label_list:
      - "bicycles"
      - "boats"
      - "bridges"
      - "bus"
      - "cars"
      - "chimneys"
      - "crosswalks"
      - "firehydrant"
      - "motorcycles"
      - "mountain"
      - "palmtrees"
      - "parkingmeters"
      - "stairs"
      - "taxis"
      - "tractors"
      - "trafficlights"


AMP:
  use_amp: False
  use_fp16_test: False
  scale_loss: 128.0
  use_dynamic_loss_scaling: True
  use_promote: False
  level: O1

Infer:
  transforms:
    - DecodeImage:
        to_rgb: True
        channel_first: False
        img_type: float32
    - ConvertDataType:
        dtype: float32
    - ResizeImage:
        resize_short: 256
    - CropImage:
        size: 224
    - NormalizeImage:
        scale: 1.0/255.0
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    - ToCHWImage:
  PostProcess:
    name: Topk
    topk: 5